# Generated by Django 4.1.5 on 2023-04-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_company_owner_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Owner',
            new_name='owner',
        ),
    ]
