# Generated by Django 4.1.5 on 2023-04-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
